# Generated by Django 4.0.3 on 2024-08-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
